### ISSUE TITLE
Better error-handling for scripts that fail to load

### ISSUE THREAD

**Issue by gregersrygg** [gardr/ext#6]
Suggestion from Michał Skinder:
> If the URL itself is bad (404, 500, slow response, whatever), the gardr <iframe> stays blank and uses the placement space. Is there a possibility to check, if actually something was returned from provided endpoint or if the iframe actually got some content, and if not- pass back that info to host for further actions (like collapsing the <iframe> or, I don't know, even reloading it) ?
This should be optional too.

**Comment by sveisvei** [comment]
@gregersrygg closing this, can be solved in a plugin, right?

**Comment by gregersrygg** [comment]
I think error-handling is a good candidate for core if it can be solved in a clean way. We could experiment with hooking up onerror and timeouts on injected scripts. Not sure if it's possible on scripts that are injected with document.write, but I think it's worth investigating.
